#!/bin/sh

set -e

case "${1}" in
	remove)
        if [ -e /usr/share/plymouth/debian-logo.png.bak ]
        then
            mv /usr/share/plymouth/debian-logo.png.bak /usr/share/plymouth/debian-logo.png
        fi
		if [ -x /usr/sbin/update-initramfs ]
		then
			update-initramfs -u
		fi
		;;

	purge|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

		;;

	*)
		echo "postrm called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
