#! /bin/sh
set -e

#DEBHELPER#

case "$1" in
    remove|deconfigure|failed-upgrade)
	update-alternatives --remove deepin-default-background \
	    /usr/share/backgrounds/desktop.jpg

	update-alternatives --remove deepin-version \
	    /usr/lib/deepin/desktop-version
	;;
esac

