#!/bin/sh

set -e

case "${1}" in
	configure)
	    update-alternatives --install /usr/share/backgrounds/default_background.jpg \
		    deepin-default-background /usr/share/backgrounds/desktop.jpg 50

	    update-alternatives --install /etc/deepin-version \
		    deepin-version /usr/lib/deepin/desktop-version 50

	    if [ -x /usr/sbin/update-initramfs ]
	    then
		    update-initramfs -u
	    fi

        if [ -x /usr/sbin/update-grub ]
        then
            /usr/sbin/update-grub || echo "update-grub failed! Ignore..." >&2
        fi
	systemctl disable systemd-timesyncd.service || true
	systemctl disable NetworkManager-dispatcher.service || true
	sed -i 's/UTC/LOCAL/' /etc/adjtime || true
		;;

	abort-upgrade|abort-remove|abort-deconfigure)

		;;

	*)
		echo "postinst called with unknown argument \`${1}'" >&2
		;;
esac

#DEBHELPER#

exit 0
